#include "DisaAssemblyParser.h"

#include <core/Target/TargetProgram.h>
#include <antlr3.h>
#include <assert.h>
#include <DisaParser.h>
#include <DisaLexer.h>

void DisaAssemblyParser::Parse(std::string fileName)
{
    Parse(fileName, SymbolScope::GetRootScope());
}

void DisaAssemblyParser::Parse(std::string fileName, SymbolScope *scope)
{
    
    CompilationContext *context = CompilationContext::GetInstance();

    pANTLR3_INPUT_STREAM  input  = antlr3FileStreamNew((pANTLR3_UINT8)(fileName.c_str()), ANTLR3_ENC_UTF8);
   
    pDisaLexer  lxr  = DisaLexerNew(input);      // CLexerNew is generated by ANTLR
    assert(lxr != NULL);

    pANTLR3_COMMON_TOKEN_STREAM  tstream = antlr3CommonTokenStreamSourceNew(ANTLR3_SIZE_HINT, TOKENSOURCE(lxr));
    assert (tstream != NULL);

    pDisaParser psr = DisaParserNew(tstream);
    assert (psr != NULL);
    
    CompilationContext::GetInstance()->CurrentParser = psr->pParser;
    
     std::vector<TargetInstruction *> *code = psr->translation_unit(psr, scope);
    
    CompilationContext::GetInstance()->CurrentParser = NULL;   
    
    //TODO: Multiple source files
    context->Target = new TargetProgram();
    context->Target->Code = *code;
}

DisaAssemblyParser::DisaAssemblyParser()
{

}

DisaAssemblyParser::~DisaAssemblyParser()
{

}

